-- Copyright (C) 2024 PDF-builder Module - Antigravity Project
-- GPL v2 or later

CREATE TABLE IF NOT EXISTS llx_pdfbuilder_theme (
    rowid             INTEGER  NOT NULL AUTO_INCREMENT,
    entity            INTEGER  NOT NULL DEFAULT 1,
    label             VARCHAR(100) NOT NULL,
    description       TEXT,
    doc_type          VARCHAR(50) NOT NULL DEFAULT 'invoice',
    font_family       VARCHAR(100) DEFAULT 'DejaVuSans',
    font_size         TINYINT UNSIGNED DEFAULT 9,
    font_size_ref     TINYINT UNSIGNED DEFAULT 9,
    font_style_ref    VARCHAR(10) DEFAULT '',
    font_size_address TINYINT UNSIGNED DEFAULT 9,
    font_style_address VARCHAR(10) DEFAULT '',
    font_size_theader TINYINT UNSIGNED DEFAULT 8,
    font_style_theader VARCHAR(10) DEFAULT 'B',
    font_size_desc    TINYINT UNSIGNED DEFAULT 9,
    font_style_desc   VARCHAR(10) DEFAULT '',
    font_size_note    TINYINT UNSIGNED DEFAULT 8,
    font_style_note   VARCHAR(10) DEFAULT '',
    font_size_footer  TINYINT UNSIGNED DEFAULT 7,
    font_style_footer VARCHAR(10) DEFAULT '',
    font_style_freetext VARCHAR(10) DEFAULT '',
    color_font        VARCHAR(7)  DEFAULT '#333333',
    color_border      VARCHAR(7)  DEFAULT '#cccccc',
    color_header_bg   VARCHAR(7)  DEFAULT '#4a6fa1',
    color_header_txt  VARCHAR(7)  DEFAULT '#ffffff',
    color_address_bg  VARCHAR(7)  DEFAULT '#f0f4fa',
    color_address_bg2 VARCHAR(7)  DEFAULT '#f0f4fa',
    color_qrcode      VARCHAR(7)  DEFAULT '#000000',
    border_style      VARCHAR(10) DEFAULT 'solid',
    border_radius     TINYINT UNSIGNED DEFAULT 3,
    bg_opacity        DECIMAL(3,2) UNSIGNED DEFAULT 0.10,
    bg_image          VARCHAR(255),
    bg_pdf            VARCHAR(255),
    logo_alt          VARCHAR(255),
    show_logo_alt     TINYINT UNSIGNED DEFAULT 0,
    hide_main_logo    TINYINT UNSIGNED DEFAULT 0,
    logo_height       DECIMAL(5,1) DEFAULT 18.0,
    header_spacing    DECIMAL(4,1) DEFAULT 2.0,
    show_customer_code TINYINT UNSIGNED DEFAULT 0,
    reverse_address   TINYINT UNSIGNED DEFAULT 0,
    paper_format      VARCHAR(20)  DEFAULT 'A4',
    margin_top        DECIMAL(4,1) DEFAULT 10.0,
    margin_left       DECIMAL(4,1) DEFAULT 11.0,
    margin_right      DECIMAL(4,1) DEFAULT 10.0,
    margin_bottom     DECIMAL(4,1) DEFAULT 10.0,
    -- Column widths (mm)
    col_width_number  DECIMAL(4,1) DEFAULT 8.0,
    col_width_ref     DECIMAL(4,1) DEFAULT 22.0,
    col_width_desc    DECIMAL(4,1) DEFAULT 0.0,
    col_width_img     DECIMAL(4,1) DEFAULT 20.0,
    col_width_vat     DECIMAL(4,1) DEFAULT 13.0,
    col_width_puht    DECIMAL(4,1) DEFAULT 19.0,
    col_width_qty     DECIMAL(4,1) DEFAULT 13.0,
    col_width_unit    DECIMAL(4,1) DEFAULT 11.0,
    col_width_discount DECIMAL(4,1) DEFAULT 12.0,
    col_width_total   DECIMAL(4,1) DEFAULT 22.0,
    -- Display flags
    show_line_numbers TINYINT UNSIGNED DEFAULT 0,
    show_ref_column   TINYINT UNSIGNED DEFAULT 0,
    show_pictures     TINYINT UNSIGNED DEFAULT 0,
    hide_vat_column   TINYINT UNSIGNED DEFAULT 0,
    hide_puht         TINYINT UNSIGNED DEFAULT 0,
    hide_qty          TINYINT UNSIGNED DEFAULT 0,
    hide_discount     TINYINT UNSIGNED DEFAULT 0,
    show_unit         TINYINT UNSIGNED DEFAULT 0,
    show_line_ttc     TINYINT UNSIGNED DEFAULT 0,
    hide_desc_long    TINYINT UNSIGNED DEFAULT 0,
    -- Footer options
    show_fold_mark    TINYINT UNSIGNED DEFAULT 0,
    no_repeat_header  TINYINT UNSIGNED DEFAULT 0,
    show_vat_breakdown TINYINT UNSIGNED DEFAULT 0,
    hide_rib          TINYINT UNSIGNED DEFAULT 0,
    show_bon_accord   TINYINT UNSIGNED DEFAULT 0,
    show_signature    TINYINT UNSIGNED DEFAULT 0,
    show_total_weight TINYINT UNSIGNED DEFAULT 0,
    -- Free text
    freetext_height   DECIMAL(4,1) DEFAULT 12.0,
    freetext_fontsize INTEGER DEFAULT 7,
    note_public       TEXT,
    -- Status
    is_default        TINYINT UNSIGNED DEFAULT 0,
    active            TINYINT UNSIGNED DEFAULT 1,
    date_creation     DATETIME,
    tms               TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fk_user_creat     INTEGER,
    fk_user_modif     INTEGER,
    PRIMARY KEY (rowid)
) ENGINE=InnoDB;
